# Configuration that applies to all clusters, regardless of
# how they popped up.

- name: Set up LDAP authentication
  include_tasks:
    file: config-auth.yml
    apply:
      tags:
        - openshift
        - openshift.config
        - openshift.config.auth
        - openshift.config.ldap
        - openshift.config.oauth
  tags:
    - openshift
    - openshift.config
    - openshift.config.auth
    - openshift.config.ldap
    - openshift.config.oauth
    - openshift.config.auth.lockdown
    - all.lockdown

- name: Set up in-cluster networking
  include_tasks:
    file: config-network.yml
    apply:
      tags:
        - openshift
        - openshift.config
        - openshift.config.network
  tags:
    - openshift
    - openshift.config
    - openshift.config.network

- name: Set up template for new namespaces
  include_tasks:
    file: config-namespaces.yml
    apply:
      tags:
        - openshift
        - openshift.config
        - openshift.config.namespaces
  tags:
    - openshift
    - openshift.config
    - openshift.config.namespaces

- name: Scale clusters (if desired size changed since installation)
  include_tasks:
    file: config-scale.yml
    apply:
      tags:
        - openshift
        - openshift.config
        - openshift.config.scale
  tags:
    - openshift
    - openshift.config
    - openshift.config.scale
