- name: SATOSA for Quay
  when: >-
    "openshift_quay_clusters" in group_names
  include_tasks:
    file: quay-satosa.yml
    apply:
      tags:
        - openshift
        - openshift.quay
        - openshift.quay.satosa
  tags:
    - openshift
    - openshift.quay
    - openshift.quay.satosa
    - openshift.quay.satosa.keys

- name: Quay
  when: >-
    "openshift_quay_clusters" in group_names
  include_tasks:
    file: quay.yml
    apply:
      tags:
        - openshift
        - openshift.quay
        - openshift.quay.server
      vars:
        # These two variables are used when expanding variables such
        # as `quay_pod_names`, and therefore they are needed by all
        # tasks, regardless of whether they mess with
        # `ansible_connection` or not:
        ansible_oc_kubeconfig: "{{ xaasible_kubeconfig }}"
        ansible_oc_namespace: "{{ quay_namespace }}"

  tags:
    - openshift
    - openshift.quay
    - openshift.quay.server
    - openshift.quay.server.serviceaccount.delete
    - openshift.quay.server.organization.delete

- name: Quay bridge
  include_tasks:
    file: quay-bridge.yml
    apply:
      tags:
        - openshift
        - openshift.quay
        - openshift.quay.bridge
  tags:
    - openshift
    - openshift.quay
    - openshift.quay.bridge
    - openshift.quay.bridge.renew-token
