- name: Quay
  when: >-
    "openshift_quay_clusters" in group_names
  include_tasks:
    file: quay.yml
    apply:
      tags:
        - openshift
        - openshift.quay
        - openshift.quay.server
  tags:
    - openshift
    - openshift.quay
    - openshift.quay.server
    - openshift.quay.server.organization.delete

- name: Quay bridge
  include_tasks:
    file: quay-bridge.yml
    apply:
      tags:
        - openshift
        - openshift.quay
        - openshift.quay.bridge
  tags:
    - openshift
    - openshift.quay
    - openshift.quay.bridge
    - openshift.quay.bridge.renew-token
