- tags: always
  include_vars: "{{ item }}"
  with_items:
    - satosa-vars.yml
    - quay-vars.yml

- name: SATOSA Kubernetes objects
  kubernetes.core.k8s:
    definition: '{{ item }}'
  with_items: >-
    {{ lookup('template', 'satosa/satosa-k8s-objects.yaml',
       template_vars=dict(satosa_namespace=quay_namespace,
                          satosa_tequila_zip_url=satosa_tequila_zip_url))
    | from_yaml_all }}
