- tags: always
  include_vars: bastion-software-vars.yml

- name: "yq"
  get_url:
    url: https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    dest: /usr/local/bin/yq
    mode: '0755'

- name: "`oc` and `kubectl`"
  shell:
    creates: /usr/local/bin/oc # ... and /usr/local/bin/kubectl
    cmd: >-
      curl -s {{ oc_download_url }}
      | tar -C/usr/local/bin -zxvf - oc kubectl

- name: "`openshift-install` (💡⏳ ~600Mb binary!)"
  shell:
    creates: /usr/local/bin/openshift-install
    cmd: >-
      curl -s {{ openshift_install_download_url }}
      | tar -C/usr/local/bin -zxvf - openshift-install

- name: "/root/oh"
  # So that when you type `ls`, you see oh  snap
  file:
    path: /root/oh
    state: directory
