- include_vars: "{{ item }}"
  with_items:
    - access.yml
    - ssh-public-keys.yml

- name: "`{{ ansible_user }}` is password-less sudoer"
  copy:
    dest: "/etc/sudoers.d/{{ ansible_user }}"
    content: |
      {{ ansible_user }} ALL=(ALL) NOPASSWD: ALL

- name: "`{{ ansible_user }}`'s `.ssh/authorized_keys`"
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    comment: "{{ item }}"
    key: >
      {{ ssh_public_keys_people[item] | coerce_list | join(" ") }}
  with_items: >-
    {{ ssh_acls[inventory_hostname] }}
