- tags: always
  include_vars: "{{ item }}"
  with_items:
    - access.yml
    - ssh-public-keys.yml
    - resources.yml
    - bastion-vsphere-vars.yml

- name: '{{ bastion_vsphere_ova_image_local_copy | dirname }}'
  delegate_to: localhost
  file:
    state: directory
    path: '{{ bastion_vsphere_ova_image_local_copy | dirname }}'

- name: OVA file on the operator's workstation
  get_url:
    url: '{{ bastion_vsphere_ova_image }}'
    dest: '{{ bastion_vsphere_ova_image_local_copy }}'

- name: Bastion VM (💡 Expect warning on vSphere 7.0.3)
  # our version of vCenter (7.0.3) doesn't know about the
  # `enableMPTSupport` `vmw:Config` option, which the latest Ubuntu
  # Jenny image uses; and that causes a server-side parse warning.
  # Fixing that correctly would be pretty onerous, as it requires
  # patching the OVA image on the operator's workstation (in turn
  # requiring more tools, storage and compute).
  community.vmware.vmware_deploy_ovf:
    name: '{{ inventory_hostname }}'
    hostname: '{{ inventory_vsphere_credentials.host }}'
    username: '{{ inventory_vsphere_credentials.user }}'
    password: '{{ inventory_vsphere_credentials.password }}'

    datacenter: '{{ bastion_vm_placement.dc }}'
    folder: '{{ bastion_vm_placement_folder_full }}'
    cluster: '{{ bastion_vm_placement.cluster }}'
    datastore: '{{ bastion_vm_placement.datastore }}'
    resource_pool: '{{ bastion_vm_placement.resource_pool }}'
    networks: "{u'VM Network':u'{{ bastion_vm_placement.network.name }}'}"
    ovf: '{{ bastion_vsphere_ova_image_local_copy }}'
    power_on: true
    wait_for_ip_address: true
    inject_ovf_env: true  # Otherwise “properties” below has no effect; ask
                          # me how I know
    properties:
      public-keys: |
        {% for authorized in ssh_acls[inventory_hostname] %}
        {%   for key in ssh_public_keys_people[authorized] | coerce_list %}
        {{ key }} {{ authorized }}
        {%   endfor %}
        {% endfor %}
