- include_vars: "{{ item }}"
  with_items:
    - resources.yml
    - bastion-vsphere-vars.yml

- name: "Enumerate VMs in {{ bastion_vm_placement_folder_full }}"
  community.vmware.vmware_vm_info:
    hostname: '{{ inventory_vsphere_credentials.host }}'
    username: '{{ inventory_vsphere_credentials.user }}'
    password: '{{ inventory_vsphere_credentials.password }}'

    folder: '{{ bastion_vm_placement_folder_full }}'
  register: _bastion_vm

- name: Obtain bastion IP
  set_fact:
    ansible_host: >-
      {{ _first_network_interface["ipv4"][0] }}
  vars:
    _vm_info: >-
      {{
      _bastion_vm.virtual_machines
      | selectattr("guest_name", "==", inventory_hostname)
      | first
      }}
    _first_network_interface: >-
      {{ (_vm_info.vm_network.values() | list)[0] }}
