- when: >-
    "\\" not in inventory_vsphere_credentials.user
  pause:
    seconds: 1
    prompt: |

      ⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠

      Please use fully qualified vSphere username i.e. INTRANET\{{ _user }},
      rather than {{ _user }}.

      ⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠

  vars:
    _user: >-
      {{ inventory_vsphere_credentials.user }}

- fail: {}
  when: >-
    "\\" not in inventory_vsphere_credentials.user

- include_tasks:
    file: bastion-vm.yml
    apply:
      tags:
        - bastion
        - bastion.vm
      vars:
        ansible_connection: local          # The VM may not even exist yet
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
      environment:
        VMWARE_VALIDATE_CERTS: false
  tags:
    - bastion
    - bastion.vm

- tags: always
  include_tasks:
    file: bastion-get-IP.yml
    apply:
      tags: always
      vars:
        ansible_connection: local          # We don't know the IP yet
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
      environment:
        VMWARE_VALIDATE_CERTS: false

- include_tasks:
    file: bastion-access.yml
    apply:
      tags:
        - bastion
        - bastion.access
  tags:
    - bastion
    - bastion.access

- include_tasks:
    file: bastion-software.yml
    apply:
      tags:
        - bastion
        - bastion.software
  tags:
    - bastion
    - bastion.software

- include_tasks:
    file: bastion-vsphere-CA.yml
    apply:
      tags:
        - bastion
        - bastion.ca
        - bastion.CA
  tags:
    - bastion
    - bastion.ca
    - bastion.CA

- include_tasks:
    file: bastion-motd.yml
    apply:
      tags:
        - bastion
        - bastion.motd
  tags:
    - bastion
    - bastion.motd

- include_tasks:
    file: bastion-xaasctl.yml
    apply:
      tags:
        - bastion
        - bastion.xaasctl
        - all.xaasctl
      delegate_to: localhost
      vars:
        ansible_connection: local  # So that Ansible won't attempt to ssh
                                   # to localhost 🤦
  tags:
    - bastion
    - bastion.xaasctl
    - all.xaasctl
