satosa_image: satosa:8
# `docker run --rm satosa:8 id` says that the user `satosa` has ID 1000 in the image:
satosa_run_as_user: 1000

satosa_log_level: DEBUG

satosa_tech_support_email: 1234@epfl.ch
satosa_tequila_hostname_short: tequila
satosa_tequila_hostname: "{{ satosa_tequila_hostname_short }}.epfl.ch"

satosa_keybase:
  oidc_private_key: "{{ inventory_quay_satosa_secrets_folder }}/oidc-frontend.key"
  oidc_certificate: "{{ inventory_quay_satosa_secrets_folder }}/oidc-frontend.crt"
  saml_private_key: "{{ inventory_quay_satosa_secrets_folder }}/satosa-backend.key"
  saml_certificate: "{{ inventory_quay_satosa_secrets_folder }}/satosa-backend.crt"

satosa_base_url: "https://{{ satosa_hostname }}"
satosa_tequila_saml_entity_name: tequila
satosa_tequila_saml_entity_id: "{{ satosa_base_url }}/{{ satosa_tequila_saml_entity_name }}"
satosa_tequila_saml_metadata_url: "https://{{ satosa_tequila_hostname }}/metadata.{{ satosa_tequila_hostname_short }}-IdP-new.xml"

oidc_clients:
  - client_id: si-quay
    client_secret: si-quay
    token_endpoint_auth_method: client_secret_post
    redirect_uris:
    - https://si-quay.epfl.ch/oauth2/satosa/callback
    response_types:
    - code
