satosa_image: satosa:8

satosa_entity_id: https://tkgi-satosa.epfl.ch/tequila   # TODO: temporary!! See https://go.epfl.ch/INC0585871
satosa_base_url: https://{{ quay_hostname }}

satosa_tequila_tag: v1.0.9
satosa_tequila_zip_url: >-
  https://github.com/epfl-si/satosa-tequila/archive/refs/tags/{{ satosa_tequila_tag }}.zip

satosa_oidc_clients:
  - client_id: si-quay
    client_secret: si-quay
    token_endpoint_auth_method: client_secret_post
    redirect_uris:
    - https://si-quay.epfl.ch/oauth2/satosa/callback
    response_types:
    - code
    tequila_requires:
      - group: si-quay-admin
