- name: "xaas-ingress: route HTTP traffic within the cluster"
  hosts: all
  gather_facts: no
  roles:
    - role: roles/xaas-ingress

- name: "xaas-monitoring: kube-prometheus"
  hosts: all
  gather_facts: no
  roles:
    - role: roles/xaas-monitoring

- name: "xaas-build: build in the cloud"
  hosts: all
  gather_facts: no
  roles:
    - role: roles/xaas-build
