#!/bin/bash
#
# This is a wrapper around ansible / ansible-playbook.
#
# Usage ("ansible" mode):
#
#   ./xaasible -m raw all -a 'date'
#
# Usage ("ansible-playbook" mode):
#
#   ./xaasible -l prod
#
#
# If you are unfamiliar with Ansible, read up on it at
# - https://www.ansible.com/overview/how-ansible-works
# - https://github.com/jdauphant/awesome-ansible

cd "$(cd $(dirname "$0"); /bin/pwd)"

ensure_ansible () {
    if ! test -f ansible-deps-cache/.versions 2>/dev/null; then
        ensure_libxmlsec1
        curl https://raw.githubusercontent.com/epfl-si/ansible.suitcase/master/install.sh | \
            SUITCASE_DIR=$PWD/ansible-deps-cache \
            SUITCASE_PIP_EXTRA="bcrypt passlib kubernetes pyvmomi ldap3 python3-saml" \
            SUITCASE_ANSIBLE_VERSION=6.3.0 \
            SUITCASE_ANSIBLE_REQUIREMENTS=requirements.yml \
            bash -x
    fi

    . "$PWD"/ansible-deps-cache/lib.sh
    ensure_ansible_runtime
}

ensure_libxmlsec1 () {
    local xmlsec1_version="$(pkg-config --print-provides xmlsec1)"
    local macosx_downgrade_bugware_explainer="
Because of some (temporary?) lack of maintenance in python-xmlsec (see
https://github.com/xmlsec/python-xmlsec/issues/254 ), you have to make
sure to install an older version:

   wget -O /tmp/libxmlsec1.rb https://raw.githubusercontent.com/Homebrew/homebrew-core/7f35e6ede954326a10949891af2dba47bbe1fc17/Formula/libxmlsec1.rb
   brew install --formula /tmp/libxmlsec1.rb
   brew pin libxmlsec1

"
    case "$xmlsec1_version" in
        "")
            cat >&2 <<'PLEASE_INSTALL_XMLSEC1'
Fatal: libxmlsec1 (+ development kit) is required for python3-saml.
PLEASE_INSTALL_XMLSEC1
            case "$(uname -s)" in
                Linux)
                    echo >&2; echo >&2 'Bailing out.' ;;
                Darwin)
                    echo >&2 "$macosx_downgrade_bugware_explainer" ;;
            esac
            exit 1;;

        *"= 1.3."*)
            case "$(uname -s)" in
                Darwin)
                    cat >&2 <<"PLEASE_DOWNGRADE_XMLSEC1"
Fatal: version 1.3.x of xmlsec1 detected; please downgrade.
$macosx_downgrade_bugware_explainer
PLEASE_DOWNGRADE_XMLSEC1
                    exit 1 ;;
            esac ;;
    esac
}

ensure_oc () {
    oc --help > /dev/null || fatal <<'PLEASE_INSTALL_OC'

The `oc` command line tool is required. Bailing out.

Please install the `oc` command-line tool on your system, and try
again.

Installation instructions can be found at
https://docs.openshift.com/container-platform/latest/cli_reference/openshift_cli/getting-started-cli.html


PLEASE_INSTALL_OC
}

ensure_openssl () {
    openssl version > /dev/null || fatal <<'PLEASE_INSTALL_OPENSSL'

The `openssl` command line tool is required. Bailing out.

Please install the `openssl` command-line tool on your system, and try
again.

PLEASE_INSTALL_OPENSSL
}

ensure_curl () {
    curl --version > /dev/null || fatal <<'PLEASE_INSTALL_CURL'

The `curl` command line tool is required. Bailing out.

Please install the `curl` command-line tool on your system, and try
again.

PLEASE_INSTALL_CURL
}


inventories () {
    echo "-i inventory/openshift-0.yml"
}

###########################################################################

set -e

ensure_ansible
ensure_oc
ensure_openssl
ensure_curl
playbook_flags="$(ansible_flag_set_var_homedir xaasible_dir)"

mode=ansible-playbook

while [ "$#" -gt 0 ]; do
  case "$1" in
        kubectl)
            mode="kubectl"
            shift ; break ;;
        -m) mode=ansible
            ansible_args+=("-m")
            shift ;;
        *)
            ansible_args+=("$1")
            shift ;;
    esac
done

case "$mode" in
    ansible-playbook)
        ansible-playbook $playbook_flags $(inventories) "${ansible_args[@]}" \
                         -e @vars/xaasible-vars.yml -e @vars/openshift-vars.yml \
                         playbook.yml
        ;;
    ansible)
        ansible $(inventories) "${ansible_args[@]}"
        ;;
    kubectl)
        kubectl "$@" ;;
esac
