# config/openid_connect_frontend.yaml for SATOSA
module: satosa.backends.saml2.SAMLBackend
name: Saml2
config:
  mirror_force_authn: no
  memorize_idp: no
  use_memorized_idp_when_force_authn: no

  sp_config:
    key_file: /saml2-backend-secrets/satosa.key
    cert_file: /saml2-backend-secrets/satosa.crt
    organization: {display_name: EPFL-eSign, name: EPFL, url: 'http://www.epfl.ch'}
    contact_person:
    - {contact_type: technical, email_address: {{ satosa_tech_support_email }}, given_name: Technical}
    - {contact_type: support, email_address: 1234@epfl.ch, given_name: Support}

    entityid: "{{ satosa_tequila_saml_entity_id }}"
    metadata:
      remote:
        - url: "{{ satosa_tequila_saml_metadata_url }}"
          cert: /tequila-secrets/tequila-cert.pem

    accepted_time_diff: 60
    service:
      sp:
        name_id_format: 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient'
        # A name_id_format of 'None' will cause the authentication request to not
        # include a Format attribute in the NameIDPolicy.
        # name_id_format: 'None'
        name_id_format_allow_create: true
