# The so-called “iteration 0” of OpenShift 4 @ EPFL.

bastions:
  hosts:
    bastion-ocp-t:
      inventory_openshift_iteration: 0
      # Used in ../roles/bastion-vm/vars/bastion-vsphere-vars.yml, and
      # also as a key to the top-level dict of the Keybase file
      # referenced on the next line:
      inventory_vsphere_name: vsphere-test
      inventory_vsphere_credentials_keybase_file: >-
        /keybase/team/epfl_ocpnext.test/vsphere-credentials.yml
      # Should contain keys `host`, `user` and `password`. ⚠ `user`
      # must be the fully qualified name, i.e.
      # `INTRANET\vsissp-ocp-svc-t-01` rather than
      # `vsissp-ocp-svc-t-01`! Otherwise, the install will proceed
      # smoothly, up until the point where the VMware CSI driver needs
      # to create volumes. Because said driver's controller
      # introspects its own permissions to figure out volume placement
      # topologies; and it is not very smart about the idea that the
      # same user can have more than one username;
      # https://access.redhat.com/support/cases/#/case/03611844
      # ensues.
  vars:
    inventory_vsphere_credentials: >-
        {{ lookup("pipe", "keybase fs read " +
                          inventory_vsphere_credentials_keybase_file)
        | from_yaml }}

openshift_clusters:
  vars:
    inventory_quay_s3_credentials: >-
        {{ lookup("pipe", "keybase fs read " +
                          inventory_quay_s3_credentials_keybase_file)
        | from_yaml }}
  children:
    openshift_hub_clusters:
      hosts:
        mgmt.ocp-test.epfl.ch:
          inventory_bastion: bastion-ocp-t
          inventory_quay_s3_credentials_keybase_file: /keybase/team/epfl_ocpnext.test/scality-quay-bucket.yml
          inventory_quay_satosa_secrets_folder: /keybase/team/epfl_ocpnext.test/satosa
    openshift_spoke_clusters:
      hosts:
        iam.ocp-test.epfl.ch:
          inventory_hub_cluster: mgmt.ocp-test.epfl.ch

        fsd.ocp-test.epfl.ch:
          inventory_hub_cluster: mgmt.ocp-test.epfl.ch

        camptocamp.ocp-test.epfl.ch:
          inventory_hub_cluster: mgmt.ocp-test.epfl.ch

# Clusters that have Quay installed
openshift_quay_clusters:
  hosts:
    mgmt.ocp-test.epfl.ch:
