# The so-called “iteration 0” of OpenShift 4 @ EPFL.

bastions:
  hosts:
    bastion-ocp-t:
      inventory_openshift_iteration: 0
      # Used in ../roles/bastion-vm/vars/bastion-vsphere-vars.yml, and
      # also as a key to the top-level dict of
      # /keybase/team/epfl_idevfsd/OpenShift-4/vsphere-credentials.yml :
      inventory_vsphere_name: vsphere-test
      inventory_vsphere_credentials_keybase_file: >-
        /keybase/team/epfl_idevfsd/OpenShift-4/vsphere-credentials-test.yml
  vars:
    inventory_vsphere_credentials: >-
        {{ lookup("pipe", "keybase fs read " +
                          inventory_vsphere_credentials_keybase_file)
        | from_yaml }}

openshift_clusters:
  children:
    openshift_hub_clusters:
      hosts:
        mgmt.ocp-test.epfl.ch:
          inventory_bastion: bastion-ocp-t
    openshift_spoke_clusters:
      hosts:
        iam.ocp-test.epfl.ch:
          inventory_hub_cluster: mgmt.ocp-test.epfl.ch

        fsd.ocp-test.epfl.ch:
          inventory_hub_cluster: mgmt.ocp-test.epfl.ch

        camptocamp.ocp-test.epfl.ch:
          inventory_hub_cluster: mgmt.ocp-test.epfl.ch
