- include_vars: "{{ item }}"
  tags: always
  with_items:
    - nginx-vars.yml
    - vars/entrypoints.yml
    - vars/common-vars.yml

- name: nginx ingress-controller
  include_tasks:
    file: nginx-tasks.yml
    apply:
      tags:
        - nginx
  tags:
    - nginx
    - nginx.wipe
