# Kubernetes objects to run SATOSA in a cluster

apiVersion: v1
kind: Namespace
metadata:
  name: {{ satosa_namespace }}

---

apiVersion: v1
kind: Deployment
metadata:
  name: satosa
  namespace: {{ satosa_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: satosa
  template:
    metadata:
      labels:
        service: satosa
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ satosa_run_as_user }}
      containers:
        - name: satosa
          image: {{ satosa_image }}
          volumeMounts:
            - name: config
              subPath: proxy_conf.yaml
              mountPath: /etc/satosa/proxy_conf.yaml
            - name: config
              mountPath: /config
      ports:
        - containerPort: 8080
          name: http
      volumes:
        - name: config
          configMap:
            name: satosa

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: satosa
  namespace: {{ satosa_namespace }}
data:
  proxy_conf.yaml: |
    {{ lookup("template", "proxy_conf.yaml") | indent(4) }}
  openid_connect_frontend.yaml: |
    {{ lookup("template", "satosa-modules/openid_connect_frontend.yaml") | indent(4) }}
  static_attributes_microservice.yaml: |
    {{ lookup("template", "satosa-modules/static_attributes_microservice.yaml") | indent(4) }}
  saml2_backend.yaml: |
    {{ lookup("template", "satosa-modules/saml2_backend.yaml") | indent(4) }}
