- tags: always
  include_vars: spoke-vars.yml

- name: "Spoke cluster: basic objects"
  include_tasks:
    file: spoke-prep.yml
    apply:
      tags:
        - openshift
        - openshift.spoke
        - openshift.spoke.install
        # During install, talk to the parent (hub) cluster:
      environment:
        KUBECONFIG: >-
          {{ spoke_kubeconfig_of_hub }}
  tags:
    - openshift
    - openshift.spoke
    - openshift.spoke.install

- name: Install or reconnect to spoke cluster
  when: inventory_manually_created_cluster_name is not defined
  include_tasks:
    file: spoke-install.yml
    apply:
      environment:
        KUBECONFIG: >-
          {{ spoke_kubeconfig_of_hub }}
      tags:
        - openshift
        - openshift.spoke
        - openshift.spoke.install
  tags:
    - openshift
    - openshift.spoke
    - openshift.spoke.install

- include_tasks:
    file: spoke-xaasctl.yml
    apply:
      tags:
        - openshift
        - openshift.spoke
        - openshift.spoke.xaasctl
        - all.xaasctl
      delegate_to: localhost
      vars:
        ansible_connection: local
      # Likewise, we have to pick up CA bundles etc. from the parent
      # (hub) cluster:
      environment:
        KUBECONFIG: >-
          {{ spoke_kubeconfig_of_hub }}
  tags:
    - openshift
    - openshift.spoke
    - openshift.spoke.xaasctl
    - all.xaasctl

- tags: always
  name: Log in to managed clusters
  changed_when: false  # Eh. It only changes a cache.
  shell:
    cmd: |
      env KUBECONFIG={{ xaasible_kubeconfig }} ./xaasctl login-cluster {{ inventory_hostname }}
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

- include_tasks:
    file: spoke-backdoor.yml
    apply:
      tags:
        - openshift
        - openshift.spoke
        - openshift.spoke.backdoor
      environment:
        KUBECONFIG: "{{ xaasible_kubeconfig }}"  # Unless stipulated otherwise inside spoke-backdoor.yml
  tags:
    - openshift
    - openshift.spoke
    - openshift.spoke.backdoor
