- tags: always
  include_vars: spoke-vars.yml

- name: "Spoke cluster: prepare"
  include_tasks:
    file: spoke-prep.yml
    apply:
      tags:
        - openshift
        - openshift.spoke
        - openshift.spoke.prep
  tags:
    - openshift
    - openshift.spoke
    - openshift.spoke.prep

- name: Install spoke cluster
  when: inventory_manually_created_cluster_name is not defined
  include_tasks:
    file: spoke-install.yml
    apply:
      tags:
        - openshift
        - openshift.spoke
        - openshift.spoke.install
  tags:
    - openshift
    - openshift.spoke
    - openshift.spoke.install

- include_tasks:
    file: spoke-xaasctl.yml
    apply:
      tags:
        - openshift
        - openshift.spoke
        - openshift.spoke.xaasctl
        - all.xaasctl
      delegate_to: localhost
      vars:
        ansible_connection: local
  tags:
    - openshift
    - openshift.spoke
    - openshift.spoke.xaasctl
    - all.xaasctl

- tags: always
  name: Log in to managed clusters
  changed_when: false  # Eh. It only changes a cache.
  shell:
    cmd: |
      env KUBECONFIG={{ xaasible_kubeconfig }} ./xaasctl login-cluster {{ inventory_hostname }}
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

- include_tasks:
    file: spoke-backdoor.yml
    apply:
      tags:
        - openshift
        - openshift.spoke
        - openshift.spoke.backdoor
      environment:
        KUBECONFIG: "{{ xaasible_kubeconfig }}"  # Unless countermanded inside spoke-backdoor.yml
  tags:
    - openshift
    - openshift.spoke
    - openshift.spoke.backdoor
