- shell:
    creates: "{{ xaasible_cache_dir }}/xaasctl-inventory.sh"
    cmd: |
      mkdir -p {{ xaasible_cache_dir }} || true
      touch {{ xaasible_cache_dir }}/xaasctl-inventory.sh

- name: Update xaasible-state-cache/xaasctl-inventory.sh with findings from this role
  blockinfile:
    path:  "{{ xaasible_cache_dir }}/xaasctl-inventory.sh"
    marker: "# {mark} {{ inventory_hostname }} declarations from spoke-xaasctl.yml"
    block: |
      {%   set _cluster_name_shell = inventory_hostname | regex_replace('[-.]', '_') %}

      cluster_{{ _cluster_name_shell }}_fqdn={{ inventory_hostname }}

      cluster_{{ _cluster_name_shell }}_access () {
        echo "spoke"
      }

      cluster_{{ _cluster_name_shell }}_cluster_hub_name () {
        echo {{ inventory_hub_cluster | regex_replace('[-.]', '_') }}
      }

      cluster_{{ _cluster_name_shell }}_cluster_hub_namespace () {
        echo {{ spoke_namespace_in_hub }}
      }

      cluster_{{ _cluster_name_shell }}_ca_bundle () {
        echo "{{ cluster_local_ca_bundle_file }}"
      }

- name: Obtain ingress certificates
  changed_when: false
  shell: |
    set -e -x
    spew="$(openssl s_client -verify_quiet -showcerts \
            -connect {{ _oauth_fqdn }}:443 < /dev/null)"
    echo "$spew" | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'
  register: _ingress_certificates
  vars:
    _oauth_fqdn: "oauth-openshift.apps.{{ inventory_hostname }}"

- name: Obtain loadbalancer signer
  changed_when: false
  shell:
    cmd: |
      set -e -x
      env KUBECONFIG="{{ xaasible_kubeconfig }}" \
        oc -n openshift-kube-apiserver-operator get secret/loadbalancer-serving-signer \
      {% raw %} -o template='{{ index .data "tls.crt" | base64decode }}' {% endraw %}
  register: _spoke_lb_signer

- name: Spoke CA bundles
  copy:
    dest: "{{ cluster_local_ca_bundle_file }}"
    content: |
      {{ _spoke_lb_signer.stdout }}
      {{ _ingress_certificates.stdout }}
