spoke_namespace_in_hub: >-
  {{ inventory_manually_created_cluster_name
  | default("managed-cluster-%s" %
  (inventory_hostname | regex_replace("\..*$", "")))
  }}

spoke_kubeadmin_ownerReference:
  apiVersion: v1
  kind: Secret
  name: kubeadmin
  uid: >-
    {{ lookup("pipe",
    "KUBECONFIG={{ xaasible_kubeconfig }} oc -n kube-system get secret kubeadmin
    -o jsonpath='{.metadata.uid}'") }}

spoke_kubeconfig_of_hub: >-
  {{ hostvars[inventory_hub_cluster].xaasible_kubeconfig }}

_spoke_reconnected_secrets_prefix: >-
  {{ spoke_namespace_in_hub }}-reconnected

spoke_reconnected_secret_admin_kubeconfig: >-
  {{ _spoke_reconnected_secrets_prefix }}-admin-kubeconfig

spoke_reconnected_secret_admin_password: >-
  {{ _spoke_reconnected_secrets_prefix }}-admin-password
