- tags: always
  include_vars: hubble-vars.yml

- name: Set up Cilium for network observability
  include_tasks:
    file: security-cilium.yml
    apply:
      tags:
        - openshift
        - openshift.security
        - openshift.security.cilium
  tags:
    - openshift
    - openshift.security
    - openshift.security.cilium

- name: Set up template for new namespaces
  include_tasks:
    file: security-namespaces.yml
    apply:
      tags:
        - openshift
        - openshift.security
        - openshift.security.namespaces
  tags:
    - openshift
    - openshift.security
    - openshift.security.namespaces

- when: >-
    inventory_hostname == hubble_build_on_cluster
  name: Build custom Hubble image
  include_tasks:
    file: security-hubble-build.yml
    apply:
      tags:
        - openshift
        - openshift.security
        - openshift.security.hubble
        - openshift.security.hubble.build
  tags:
    - openshift
    - openshift.security
    - openshift.security.hubble
    - openshift.security.hubble.build
