- tags: always
  include_vars: versions.yml

- name: Quay service account for the Hubble UI images
  quay_service_account:
    name: "{{ hubble_quay_service_account_name }}"

- name: Quay organization for the Hubble UI images
  quay_organization:
    name: "{{ hubble_quay_organization_name }}"
    email: "si-quay-admin@groupes.epfl.ch"
    owner: "{{ hubble_quay_service_account_name }}"

- name: Robot account to push Hubble images
  quay_robot_account:
    organization:    "{{ hubble_quay_organization_name }}"
    robot_shortname:  "{{ hubble_build_robot_account_shortname }}"
  register: _hubble_quay_build_token

- name: "`{{ hubble_build_namespace }}` namespace"
  kubernetes.core.k8s:
    definition:
      kind: Namespace
      metadata:
        name: "{{ hubble_build_namespace }}"

- name: Secret that contains the robot account's token
  kubernetes.core.k8s:
    definition:
      kind: Secret
      metadata:
        namespace: '{{ hubble_build_namespace }}'
        name: "{{ hubble_build_push_secret_name }}"
      type: kubernetes.io/dockerconfigjson
      stringData:
        .dockerconfigjson: "{{ _docker_auths_yaml | from_yaml | to_json }}"
  vars:
    _docker_auths_yaml: |
      auths:
        {{ quay_hostname }}:
          auth: "{{ _loginpassword | b64encode }}"
          email: ""
    _loginpassword: "{{ _login }}:{{ _token }}"
    _login: "{{ hubble_build_robot_account }}"
    _token: "{{ _hubble_quay_build_token.token }}"

- name: "Link push secret to builder service account"
  kubernetes.core.k8s:
    definition:
      kind: ServiceAccount
      metadata:
        name: builder
        namespace: "{{ hubble_build_namespace }}"
      secrets:
        - name: "{{ hubble_build_push_secret_name }}"

- include_tasks:
    file: _hubble_homebuilt_image.yml
  vars:
    _image_name: "{{ item.image.name }}"
    _image_tag: "{{ item.image.tag }}"
    _git_url:    "{{ item.git.url }}"
    _git_ref:    "{{ item.git.ref | default('refs/heads/master') }}"
  with_items:
    - image:
        name: "{{ hubble_okd_image_name }}"
        tag: "{{ hubble_okd_epfl_version }}"
      git:
        url: "{{ hubble_okd_git_repository }}"
        ref: "refs/tags/v{{ hubble_okd_epfl_version }}"
    - image:
        name: "{{ hubble_ui_image_name }}"
        tag: "{{ hubble_ui_epfl_version }}"
      git:
        url: "{{ hubble_ui_git_repository }}"
        ref: "refs/tags/{{ hubble_ui_epfl_version }}"
