- name: Set up OVN-Kubernetes default IPv4 range
  kubernetes.core.k8s:
    definition:
      apiVersion: operator.openshift.io/v1
      kind: Network
      metadata:
        name: cluster  # Not namespaced (and should already exist)
      spec:
        defaultNetwork:
          type: OVNKubernetes
          ovnKubernetesConfig:
            v4InternalSubnet: 172.31.0.0/16

- name: `cilium` Helm repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/
