- tags: always
  include_vars: "{{ item }}"
  with_items:
    - resources.yml
    - cilium-vars.yml

- name: Rebuild CiliumConfig object
  # Note: this object will necessarily already exist, as it is created
  # as part of the cluster install. We may want to change it
  # post-install in some circumstances, though.
  tags:
    - openshift.cilium
    - openshift.cilium.config
  kubernetes.core.k8s:
    definition: >-
      {{ lookup("template", "cluster-network-07-cilium-ciliumconfig.yaml",
                           template_vars=dict(networkConfig=resources_openshift_clusters[inventory_hostname])) }}

- when: >-
    inventory_hostname == cilium_hubble_ui_build_on_cluster
  include_tasks:
    file: cilium-hubble-ui-build.yml
    apply:
      tags:
        - openshift
        - openshift.cilium
        - openshift.cilium.hubble
        - openshift.cilium.hubble.build
        - openshift.cilium.hubble.rebuild
  tags:
    - openshift
    - openshift.cilium
    - openshift.cilium.hubble
    - openshift.cilium.hubble.build
    - openshift.cilium.hubble.rebuild

- include_tasks:
    file: cilium-hubble-ui-run.yml
    apply:
      tags:
        - openshift
        - openshift.cilium
        - openshift.cilium.hubble
        - openshift.cilium.hubble.run
  tags:
    - openshift
    - openshift.cilium
    - openshift.cilium.hubble
    - openshift.cilium.hubble.run
