satosa_namespace: satosa-system
satosa_image: satosa:8
# `docker run --rm satosa:8 id` says that the user `satosa` has ID 1000 in the image:
satosa_run_as_user: 1000

# The host name under which the SATOSA front-end side is reachable
satosa_hostname: tkgi-satosa.epfl.ch

satosa_log_level: DEBUG

satosa_tech_support_email: dominique.quatravaux@epfl.ch
satosa_tequila_hostname_short: tequila
satosa_tequila_hostname: '{{ satosa_tequila_hostname_short }}.epfl.ch'

satosa_keybase:
  oidc_private_key: /keybase/team/epfl_idevfsd/svc0176idevfsdkt0001/frontend.key
  oidc_certificate: /keybase/team/epfl_idevfsd/svc0176idevfsdkt0001/frontend.crt
  saml_private_key: /keybase/team/epfl_idevfsd/svc0176idevfsdkt0001/satosa-backend.key
  saml_certificate: /keybase/team/epfl_idevfsd/svc0176idevfsdkt0001/satosa-backend.crt

# TODO: use our own set of SAML identities
satosa_tequila_saml_entity_id: https://esign-login.epfl.ch/saml/metadata
satosa_tequila_saml_metadata_url: 'https://{{ satosa_tequila_hostname }}/metadata.{{ satosa_tequila_hostname_short }}-IDP.xml'
