bastion_vsphere_vms:
  bastion-ocp-t:
    dc: ocp-test-DC
    subfolder: ocp/management
    cluster: clstr-test-OCP-01
    resource_pool: ocp-mgmt
    datastore: clstr-test-OCP-01_vsanDatastore
    network:
        name: S-VLAN-OCP-mgmt-VNI12029

bastion_vsphere_ova_image: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.ova
bastion_vsphere_ova_image_local_copy: '{{ xaasible_dir }}/xaasible-state-cache/{{ bastion_vsphere_ova_image | basename }}'
