# Kubernetes objects to run SATOSA in a cluster

apiVersion: v1
kind: Namespace
metadata:
  name: {{ satosa_namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: si-registry-satosa-app
  namespace: {{ satosa_namespace }}

---
 apiVersion: rbac.authorization.k8s.io/v1
 kind: ClusterRoleBinding
 metadata:
   name: si-quay-satosa-insists-to-run-as-uid-1000
 roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:openshift:scc:nonroot-v2
 subjects:
 - kind: ServiceAccount
   namespace: {{ satosa_namespace }}
   name: si-registry-satosa-app

---
apiVersion: v1
kind: Deployment
metadata:
  name: satosa
  namespace: {{ satosa_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: satosa
  template:
    metadata:
      labels:
        service: satosa
    spec:
      containers:
        - name: satosa
          image: {{ satosa_image }}
          command:
            - bash
            - -x
            - /config/custom-entrypoint.sh
          ## Comment the above two lines and uncomment below
          ## to force the container to start up (for debugging
          ## purposes):
          # - sleep
          # - "36000"
          ## 💡 From a `kubectl exec` prompt, you can then run
          ##
          ##    /usr/local/bin/docker-entrypoint.sh gunicorn -b0.0.0.0:8080 satosa.wsgi:app
          ##
          ## to get the same behavior that the pod would normally run.
          volumeMounts:
            - name: config
              mountPath: /config
            - name: config
              subPath: custom-entrypoint.sh
              mountPath: /custom-entrypoint.sh
            - name: config
              subPath: proxy_conf.yaml
              mountPath: /proxy_conf.yaml
            - name: config
              mountPath: /site-python/epfl
            - name: config
              subPath: tequila_attributes.py
              mountPath: /attributemaps/tequila_attributes.py
            - name: config
              subPath: clients.json
              mountPath: /data/clients.json
          env:
            - name: PYTHONPATH
              value: /site-python
            - name: SATOSA_BASE_URL
              value: "{{ satosa_base_url }}"
            - name: SATOSA_ENTITY_ID
              value: "{{ satosa_entity_id }}"
      serviceAccount: si-registry-satosa-app
      securityContext:
        runAsUser: 1000
      ports:
        - containerPort: 8080
          name: http
      volumes:
        - name: config
          configMap:
            name: satosa

---
apiVersion: v1
kind: Service
metadata:
  name: satosa
  namespace: {{ satosa_namespace }}
spec:
  selector:
    service: satosa
  ports:
    - name: http
      port: 80
      targetPort: 8080
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: si-quay-satosa-wellknown
  namespace: {{ satosa_namespace }}
spec:
  host: {{ quay_hostname }}
  port:
    targetPort: http
  path: /.well-known
  to:
    kind: Service
    name: satosa
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

---

# The `si-registry-quay-app-XXXXX-YYYY` pods use this route to
# wrangle the OpenID-Connect API:
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: si-quay-satosa-oidc
  namespace: {{ satosa_namespace }}
spec:
  host: {{ quay_hostname }}
  port:
    targetPort: http
  path: /OIDC
  to:
    kind: Service
    name: satosa
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

---

# The browser uses this route on its way back from Tequila:
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: si-quay-satosa-tequila
  namespace: {{ satosa_namespace }}
spec:
  host: {{ quay_hostname }}
  port:
    targetPort: http
  path: /tequila
  to:
    kind: Service
    name: satosa
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
