{# Template for the file of the same name to feed to openshift-installer
 # (directly as a file on the bootstrap VM for the case of a hub cluster,
 # or via a ConfigMap that the operator consumes for a spoke cluster)
 #
 # Expected input variables:
 #
 # - networkConfig: should have the following shape,
 #
 #      networkConfig:
 #        podIPs:
 #          cidr: <IP>/<integer from 1 to 31>
 #          hostPrefix: <integer from 1 to 31>
 #        serviceIPs:
 #          cidr: <IP>/<integer from 1 to 31>
 #
 # - cluster_api_server: The hostname of the cluster's API server
 #}
apiVersion: cilium.io/v1alpha1
kind: CiliumConfig
metadata:
  name: cilium
  namespace: cilium
spec:
  sessionAffinity: true
  securityContext:
    privileged: true
  kubeProxyReplacement: true
  k8sServiceHost: "{{ cluster_api_server }}"
  k8sServicePort: 6443
  ipam:
    mode: "cluster-pool"
    operator:
      clusterPoolIPv4PodCIDRList: "{{ networkConfig.podIPs.cidr }}"
      clusterPoolIPv4MaskSize: {{ networkConfig.podIPs.hostPrefix }}
  cni:
    binPath: "/var/lib/cni/bin"
    confPath: "/var/run/multus/cni/net.d"
    exclusive: false
    customConf: false
  nodeinit:
    enabled: true
  hubble:
    enabled: true
    relay:
      enabled: true
    ui:
      enabled: true
    tls:
      auto:
        # The default value (`helm`) runs into a silly
        # upgrade-to-not-really-change-anything loop:
        method: certmanager
        certManagerIssuerRef:
          group: cert-manager.io
          kind: ClusterIssuer
          name: ca-issuer
