{# Template for the configuration file to the `openshift-install` command,
 # used by the `openshift4-bootstrap` and `openshift4-spoke` roles.
 #
 # The template relies on the following variables being set:
 #
 # - The following variables should be set explicitly by the caller:
 #   • ocp_config_resources
 #   • ocp_config_pull_secret
 #
 # - The following variables “flow” from `inventory_hostname` (i.e.
 #   they are specific to the cluster being configured):
 #   • cluster_name
 #   • cluster_base_domain
 #   • vmware_credentials
 #
 # - The following variables are “global” lookup tables, and the template
 #   explicitly walks them using `inventory_hostname` as the key:
 #   • ssh_acls
 #   • ssh_public_keys_people
 #}
{% set _it = ocp_config_resources %}
{% set _vsphere_vm_folder = "/%s/vm/%s" % (
   _it.vsphere_placement.dc,
   _it.vsphere_placement.subfolder)
%}
{% set _vsphere_resources_folder = "/%s/host/%s/Resources/%s" % (
   _it.vsphere_placement.dc,
   _it.vsphere_placement.cluster,
   _it.vsphere_placement.resource_pool)
%}
apiVersion: v1
metadata:
  name: {{ cluster_name }}
baseDomain: {{ cluster_base_domain }}
compute:
- name: worker
  architecture: {{ _it.architecture }}
  hyperthreading: {{ _it.hyperthreading }}
  platform: {}
  replicas: {{ _it.workers }}
controlPlane:
  name: master
  architecture: {{ _it.architecture }}
  hyperthreading: {{ _it.hyperthreading }}
  platform: {}
  replicas: {{ _it.masters }}
networking:
  clusterNetwork:
  - {{ _it.podIPs | to_nice_yaml | indent(4) | trim }}
  machineNetwork:
  - {{ _it.machineIPs | to_nice_yaml | indent(4) | trim }}
  networkType: OVNKubernetes
  serviceNetwork:
  - {{ _it.serviceIPs.cidr }}
platform:
  vsphere:
    cluster: {{ _it.vsphere_placement.cluster }}
    folder: {{ _vsphere_vm_folder }}
    resourcePool: {{ _vsphere_resources_folder }}
    network: {{ _it.vsphere_placement.network.name }}
    apiVIPs:
    {{ _it.apiVIPs | to_nice_yaml | indent(4) | trim }}
    datacenter: {{ _it.vsphere_placement.dc }}
    defaultDatastore: {{ _it.vsphere_placement.datastore }}
    ingressVIPs:
    {{ _it.ingressVIPs | to_nice_yaml | indent(4) | trim }}
    vCenter: {{ vsphere_credentials.host }}
    # Need heavier escaping below, as the username contains a backslash!
    username: >-
      {{ vsphere_credentials.user }}
    password: {{ vsphere_credentials.password }}
publish: External
pullSecret: '{{ ocp_config_pull_secret }}'
sshKey: |
{% for person in ssh_acls[inventory_hostname] %}
{%   for key in ssh_public_keys_people[person] | coerce_list %}
       {{ key | trim }} {{ person }}
{%   endfor %}
{% endfor %}
