- include_tasks:
    file: vcenter-roles.yml
    apply:
      tags:
        - roles
        - roles.vc
  tags:
    - roles
    - roles.vc

- include_tasks:
    file: vcenter-apply-roles-to-ocp-user.yml
    apply:
      tags:
        - roles
        - roles.vc
        - roles.vc.to.user
  tags:
    - roles
    - roles.vc
    - roles.vc.to.user