hubble_build_on_cluster: mgmt.ocp-test.epfl.ch
# hubble_build_namespace comes from ../../../vars/openshift-vars.yml
hubble_build_service_account: hubble-public
hubble_build_robot_account_shortname: "builder"
hubble_build_robot_account: "{{ hubble_quay_organization_name }}+{{ hubble_build_robot_account_shortname }}"
hubble_build_push_secret_name: >-
  {{ hubble_build_service_account }}-push

hubble_quay_organization_name: hubble-public
hubble_quay_service_account_name: si-quay-hubble

hubble_okd_image_name: okd.epfl-hubble-ui
hubble_okd_git_repository: https://github.com/epfl-si/cluster.okd.hubble-ui
# hubble_okd_epfl_version comes from ../../../vars/versions.yml
hubble_okd_qualified_image: >-
  {{ quay_hostname }}/{{ hubble_quay_organization_name }}/{{ hubble_okd_image_name }}:{{ hubble_okd_epfl_version }}
