apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  validatingWebhook: "Enabled"
## https://access.redhat.com/articles/6047221 pour des configurations supplémentaires