# - name: Delete (almost) everything in the {{ nginx_ingress_namespace }} namespace
#   tags: nginx.wipe
#   when: |
#     "nginx.wipe" in ansible_run_tags
#   ignore_errors: true
#   shell:
#     cmd: |
#       set -e -x
#       for wat in all secret; do
#         {{ xaasible_kubectl }} get $wat -n {{ nginx_ingress_namespace }} -o name
#       done | \
#         grep -v default-token | grep -v pod/ |grep -v replicaset/ | \
#         xargs {{ xaasible_kubectl }} -n {{ nginx_ingress_namespace }} delete --ignore-not-found
# 
#       {{ xaasible_kubectl }} delete --ignore-not-found ingressclass nginx

# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#uninstall-helm-chart
- name: Remove prometheus-community release and waiting suppression ending
  kubernetes.core.helm:
    name: prometheus-community
    release_namespace: "{{ monitoring_namespace }}"
    state: absent
    wait: true
  tags: prometheus.wipe
  when: |
    "prometheus.wipe" in ansible_run_tags

- name: Import prometheus-community/kube-prometheus-stack Helm repository
  kubernetes.core.helm_repository:
    repo_name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Deploy prometheus-community/kube-prometheus-stack with Helm
  kubernetes.core.helm:
    name: "{{ prometheus.helm_install_name }}"
    chart_ref: "{{ prometheus.helm_chart }}"
    release_namespace: "{{ monitoring_namespace }}"
    # Please note that the values_files is sourced first
    # and var can be redefined by the values option below.
    values_files: "{{role_path}}/files/kube-prometheus-stack-epfl.yml"
    values:
      commonLabels:
        deployer: "ISAS-FSD"
      rbac:
        create: false
        enabled: false
