apiVersion: constraints.gatekeeper.sh/v1beta1
kind: clusterstoragequota
metadata:
  name: quota-sc
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["PersistentVolumeClaim"]
  parameters:
    storagelimit: {{ quota_sc_size }}
